spring:
  application:
    name: VotaClaro
  datasource:
    url: jdbc:mysql://localhost:3306/votoClaro
    username: root
    password: 1134
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update